---
title: "Covid91 vaccine study Final2023"
author: "Jason Leon"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% mutate(infected = recode(infected, aids = "covid", none = "ok"
 )) %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
FinalData$treatment <- relevel(FinalData$treatment,ref="placebo")
#finaldata$infected <- relevel(FinalData$infected,ref="ok)
Males = filter(FinalData, sex =="Males")
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

## Males


## Females


## LGBTQ
Null hypothesis (HO): There is no diffference in the effectiveness of covid 921 vaccine between LGBTQ and non-LGBTQ individual. Alternative Hypothesis(HA): There is a difference in the effectiveness of covid921 vaccine between LGBTQ and non LGBTQ individual.

Statistical verbiage: To test the hypothesis a logistic regession analysis will be conducted to assess the association between LGBTQ status and vaccine effectiveness. The p-value threshold will be set at 0.05 for significantly.

based on the statical analysis conducted if the p-value is greater than 0,05 we fail ti reject the ull hypothesis suggesting insufficient evidence to conclude a difference. in the vaccine's effectiveness between LGBTQ and non-LGBTQ individuals. Therefore, it is recommended that both LGBTQ individuals take the covid921 vaccine.


## Druggies
Null hypothesis (H0): there is no difference in the effictiveness of covid921 vaccine between druggies and non-druggies. Alternative Hypothesis(HA): There is a difference in the effectiveness of covid921 vaccine between druggies and no-druggies.

statistical verbia: To test the hypothesis a chi-square will be conduted to analyze the association between druggies and vaccine effectiveness. The p-value threshold will be set at 0.05 for significance.

Based on the statistical analysis conducted, if the p-value is greater than 0.05 we fail to reject the null hypothesis, indicating insufficient evidence to conclude a difference in the vaccin's effectiveness between druggies and non-druggies take the covid921 vaccine
# Overall Results and Conclusions

